# Generated by Django 4.0.5 on 2022-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0002_alter_recibo_estado_alter_recibo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Creado'], [1, 'Progreso'], [3, 'Facturado']], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='tipo',
            field=models.CharField(max_length=30, verbose_name='Direccion'),
        ),
    ]
