# Generated by Django 4.0.5 on 2022-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0003_alter_recibo_estado_alter_recibo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('defecto', models.CharField(max_length=150, verbose_name='Defecto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.IntegerField(choices=[[0, 'Vendedor'], [1, 'Tecnico'], [2, 'admin2']], verbose_name='Rol')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiempoEntrega', models.CharField(max_length=50, verbose_name='Tiempo Entrega')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('valor', models.FloatField(verbose_name='Valor')),
            ],
        ),
    ]
