# Generated by Django 4.0.5 on 2022-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0004_diagnostico_empleado_pedido_producto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
