# Generated by Django 4.0.5 on 2022-08-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0005_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nroSerie',
            field=models.CharField(default=None, max_length=13, verbose_name='Nro Serie'),
            preserve_default=False,
        ),
    ]
