# Generated by Django 4.0.5 on 2022-08-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0006_producto_nroserie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
