# Generated by Django 4.0.5 on 2022-08-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoseeOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioTecnico.recibo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioTecnico.servicio')),
            ],
        ),
    ]
