# Generated by Django 4.0.5 on 2022-08-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0009_poseeos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='servicio',
            field=models.ManyToManyField(to='ServicioTecnico.servicio'),
        ),
        migrations.DeleteModel(
            name='PoseeOS',
        ),
    ]
