# Generated by Django 4.0.5 on 2022-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0010_recibo_servicio_delete_poseeos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[[0, 'Garantia'], [1, 'Sin Garantia']], default=None, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
