# Generated by Django 4.0.5 on 2022-08-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0014_diagnostico_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='equipo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ServicioTecnico.equipo'),
            preserve_default=False,
        ),
    ]
