# Generated by Django 4.0.5 on 2022-08-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0016_recibo_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ServicioTecnico.cliente'),
            preserve_default=False,
        ),
    ]
