# Generated by Django 4.0.5 on 2022-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0017_recibo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='productos',
            field=models.ManyToManyField(to='ServicioTecnico.producto'),
        ),
    ]
