# Generated by Django 4.0.5 on 2022-08-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0018_recibo_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ServicioTecnico.proveedor'),
            preserve_default=False,
        ),
    ]
