# Generated by Django 4.0.5 on 2022-08-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioTecnico', '0020_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='tipo',
            field=models.IntegerField(choices=[[0, 'Venta'], [1, 'Orden de Servicio']], verbose_name='Tipo'),
        ),
    ]
